# Linear Chimú vessel metrics

```{r load packages 3, echo=TRUE}
# load libraries
library(here)
library(tidyverse)
library(vegan)
library(RVAideMemoire)
library(ggpubr)
library(ggfortify)
library(cluster)
library(wesanderson)
library(ggExtra)
```

## Load DATA + define variables

```{r setwd ld define variables 3, echo=TRUE}
DATA <- read.csv("potmeas.csv", header = TRUE, as.is = TRUE)

# define variables
od <- DATA$od <- DATA$orifice.diameter # orifice diameter
bd <- DATA$bd <- DATA$base.diameter # base diameter
nd <- DATA$nd <- DATA$bneck.diameter # neck diameter
bl <- DATA$bl <- DATA$wide.diameter # belly diameter
h <- DATA$h <- DATA$height # height
RT <- DATA$RT <- DATA$rim.thickness # rim thickness
gp <- DATA$gp <- as.factor(DATA$form) # bottle or jar
```

## Boxplots for _variable_ by _group_

```{r boxsite, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE, fig.cap = "Boxplots of orifice diameter, base diameter, neck diameter, belly diameter, height, and rim thickness for the anthropomorphic, phytomorphic, and zoomorphic Chimú vessels used in this study."}
# boxplot of orifice diameter ~ group
odgroup <- ggplot(DATA, aes(x = gp, y = od, color = gp)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',stackdir = 'center',dotsize = 0.3) +
  scale_colour_manual(values = wes_palette("Moonrise2")) +
  labs(x = "Form", y = "Orifice Diam") +
  theme(legend.position = "none")

# boxplot of base diameter ~ group
bdgroup <- ggplot(DATA, aes(x = gp, y = bd, color = gp)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',stackdir = 'center',dotsize = 0.3) +
  scale_colour_manual(values = wes_palette("Moonrise2")) +
  labs(x = "Form", y = "Base Diam") +
  theme(legend.position = "none")

# boxplot of neck diameter ~ group
ndgroup <- ggplot(DATA, aes(x = gp, y = nd, color = gp)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',stackdir = 'center',dotsize = 0.3) +
  scale_colour_manual(values = wes_palette("Moonrise2")) +
  labs(x = "Form", y = "Neck Diam") +  
  theme(legend.position = "none")

# boxplot of belly diameter ~ group
blgroup <- ggplot(DATA, aes(x = gp, y = bl, color = gp)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',stackdir = 'center',dotsize = 0.3) +
  scale_colour_manual(values = wes_palette("Moonrise2")) +
  labs(x = "Form", y = "Belly Diam") +  
  theme(legend.position = "none")

# boxplot of height ~ group
hgroup <- ggplot(DATA, aes(x = gp, y = h, color = gp)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',stackdir = 'center',dotsize = 0.3) +
  scale_colour_manual(values = wes_palette("Moonrise2")) +
  labs(x = "Form", y = "Height") +  
  theme(legend.position = "none")

# boxplot of rim thickness ~ group
rtgroup <- ggplot(DATA, aes(x = gp, y = RT, color = gp)) + 
  geom_boxplot() +
  geom_dotplot(binaxis = 'y',stackdir = 'center',dotsize = 0.3) +
  scale_colour_manual(values = wes_palette("Moonrise2")) +
  labs(x = "Form", y = "Rim Thick") +  
  theme(legend.position = "none")

# render figure
sitefigure<-ggarrange(odgroup, bdgroup, ndgroup, blgroup, hgroup, rtgroup,
                  labels = c("b","c","d","e","f","g"),
                  ncol = 3, nrow = 2)
sitefigure
```

## Principal Components Analysis for _group_

```{r pca, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE, fig.cap="Results of Principal Components Analysis for linear metrics associated with the Chimu vessels used in this study (gray squares, anthropomorphic; orange triangles, phytomorphic; tan circles, zoomorphic)."}
# set plot parameters to plot by group
df <- DATA[c(3:8)]
pch.gps <- c(15,17)[as.factor(gp)]
col.gps <- wes_palette("Moonrise2")[as.factor(gp)]

## pca plot
pca <- autoplot(prcomp(df),
                data = DATA,
                asp = 1,
                shape = pch.gps,
                colour = "form",
                variance_percentage = TRUE,
                loadings = TRUE, 
                loadings.colour = 'blue',
                loadings.label = TRUE,
                loadings.label.size = 3,
                frame = TRUE,
                frame.type = 't') +
  scale_fill_manual(values = wes_palette("Moonrise2")) +
  scale_colour_manual(values = wes_palette("Moonrise2"))

ggMarginal(pca, groupColour = TRUE)
```

## MANOVA

```{r manova}
# perMANOVA
ceramic.matrix <- as.matrix(DATA[,3:8]) # response vars
ceramic.mat <- sqrt(ceramic.matrix) # sqrt transform
ceramic.dist <- vegdist(ceramic.mat,
                        method = 'bray') # dissimilarity matrix
set.seed(5) # make results reproducible

# model: morphology as a function of form (jar v. bottle)
ceramic.manova <- adonis2(ceramic.dist ~ form,
                          data = DATA,
                          permutations = 10000,
                          method = 'bray')

## do bottles and jars differ?
ceramic.manova
```
